services:
  - type: web
    name: arbitragem-apostas-api
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
